; Configuration PlatformIO - Drone autonome
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    ; Wire et Servo sont inclus nativement dans le framework Arduino AVR
build_flags =
    -Wall
